### ISSUE TITLE
Locket client timeout causes failure in environments with very slow dns servers

### ISSUE THREAD

**Issue by metron2** [cloudfoundry/locket#7]
https://github.com/cloudfoundry/locket/blob/e5af96fd22a0cf2d517175d5c5d896967e6966bc/locket_client.go#L56

This issue is meant to be informational. I freely concede that DNS queries should take less than 10 seconds, but this could happen to someone else.

If your DNS server takes more than 10 seconds then the locket client fails to connect. routing-api (using the locketClient) seems to ask and wait for replies from all configured dns servers. The DNS query doesn't resolve fast enough and the timeout condition is met (opps!).

As suggested on slack, we will reconfigure our deployment to use bosh-dns with those external servers as recursors instead. Not sure if the timeout could be increased or made adjustable without penalty.

**Comment by brightzheng100** [comment]
We're currently facing exactly the same issue.
So can you share more details on what you've made?

Some experiments that we have done are:
1. Adding `127.0.0.1` as the `first` external DNS server in `diego_database` works;
2. Removing all external DNS servers in `diego_database` works;
3. But adding `127.0.0.1` as the `first` external DNS server would cause some other components fail.

**Comment by emalm** [comment]
Thanks for reporting this, @metron2, and to both you and @brightzheng100 for investigating the configuration around this issue. We believe this issue results from an issue with DNS resolution in Golang 1.11 (https://github.com/golang/go/issues/27525), which is fixed in Golang 1.11.1 via the backport at https://github.com/golang/go/issues/27537. In particular, this means we would expect it to affect only Diego v2.18.0: Diego v2.17.0 and earlier use Golang 1.10 or earlier, and v2.19.0 and later use Golang 1.11.1 or later. Do you happen to know which version of Diego was deployed in your CF cluster when you encountered this issue?

Best,
Eric, CF Diego PM

**Comment by heyjcollins** [comment]
As this item has been open for quite a long time, I'm going to go ahead and close it.
